# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e651d60428618dfc31d63060c787adababb8fe2505ad193c64a240cc8b5bfd5c8f86f595f05388f1c4805ad983dbdcbef33e88df8511138d3b55d5b76f650400

test:
  secret_key_base: bb14549c79ade322cae8200e17ab57b1709e3d92ec6ab1f7f33f4b3d0414dfb999f4a21b6bf96172b381634abe8027adf9980abbf5586ab727bc78fdc990ddd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
